dubbo:
  registries:
    zk:
      timeout: 3s
      address: zookeeper://127.0.0.1:2181
  protocols:
    dubbo:
      name: dubbo
      port: 20000
  consumer:
    references:
      UserService:
        registry: zk
        protocol: dubbo
        interface: org.apache.dubbo.UserService
        cluster: failover
        methods:
          - name: GetUser
            retries: 3
  provider:
    register: true
    registry: zk
    services:
      UserService:
        registry: zk
        protocol: dubbo
        interface: org.apache.dubbo.UserService
        loadbalance: random
        warmup: 100
        cluster: failover
        methods:
          - name: GetUser
            retries: 1
            loadbalance: random